<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('media_folders', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('parent_id')->nullable()->constrained('media_folders')->nullOnDelete(); $t->string('name'); $t->string('slug'); $t->timestamps(); });
        Schema::create('media_files', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('folder_id')->nullable()->constrained('media_folders')->nullOnDelete(); $t->uuid('uuid')->nullable()->unique(); $t->string('disk')->default('public'); $t->string('path'); $t->string('filename'); $t->string('original_name')->nullable(); $t->string('mime')->nullable(); $t->bigInteger('size')->default(0); $t->integer('width')->nullable(); $t->integer('height')->nullable(); $t->string('alt')->nullable(); $t->json('meta')->nullable(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('pages', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('title'); $t->string('slug')->index(); $t->text('excerpt')->nullable(); $t->longText('body')->nullable(); $t->json('builder')->nullable(); $t->string('status')->default('draft'); $t->timestamp('published_at')->nullable(); $t->string('featured_image')->nullable(); $t->json('meta')->nullable(); $t->string('template')->nullable(); $t->integer('order')->default(0); $t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('page_revisions', function(Blueprint $t){ $t->id(); $t->foreignId('page_id')->constrained()->cascadeOnDelete(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->json('data')->nullable(); $t->timestamps(); });
        Schema::create('page_templates', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->json('blocks')->nullable(); $t->string('screenshot')->nullable(); $t->timestamps(); });
        Schema::create('reusable_blocks', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->json('blocks')->nullable(); $t->boolean('is_global')->default(false); $t->timestamps(); });
        Schema::create('categories', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->string('type')->default('post'); $t->text('description')->nullable(); $t->foreignId('parent_id')->nullable()->constrained('categories')->nullOnDelete(); $t->string('image')->nullable(); $t->timestamps(); });
        Schema::create('tags', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->timestamps(); });
        Schema::create('posts', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('category_id')->nullable()->constrained('categories')->nullOnDelete(); $t->foreignId('author_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('title'); $t->string('slug')->index(); $t->text('excerpt')->nullable(); $t->longText('body')->nullable(); $t->string('status')->default('draft'); $t->timestamp('published_at')->nullable(); $t->string('featured_image')->nullable(); $t->json('meta')->nullable(); $t->bigInteger('views')->default(0); $t->timestamps(); $t->softDeletes(); });
        Schema::create('post_tag', function(Blueprint $t){ $t->id(); $t->foreignId('post_id')->constrained()->cascadeOnDelete(); $t->foreignId('tag_id')->constrained()->cascadeOnDelete(); $t->unique(['post_id','tag_id']); });
        Schema::create('comments', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('commentable_type'); $t->unsignedBigInteger('commentable_id'); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('guest_name')->nullable(); $t->string('guest_email')->nullable(); $t->text('body'); $t->string('status')->default('pending'); $t->string('ip')->nullable(); $t->timestamps(); $t->index(['commentable_type','commentable_id']); });
        Schema::create('seo_meta', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('seoable_type'); $t->unsignedBigInteger('seoable_id'); $t->string('meta_title')->nullable(); $t->text('meta_description')->nullable(); $t->string('canonical')->nullable(); $t->string('robots')->nullable(); $t->string('og_title')->nullable(); $t->text('og_description')->nullable(); $t->string('og_image')->nullable(); $t->string('twitter_card')->nullable(); $t->text('schema')->nullable(); $t->timestamps(); $t->unique(['seoable_type','seoable_id']); });
    }
    public function down(): void { foreach(['seo_meta','comments','post_tag','posts','tags','categories','reusable_blocks','page_templates','page_revisions','pages','media_files','media_folders'] as $tb) Schema::dropIfExists($tb); }
};
