<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('forms', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->text('description')->nullable(); $t->json('settings')->nullable(); $t->boolean('is_active')->default(true); $t->string('submit_text')->default('Submit'); $t->timestamps(); });
        Schema::create('form_fields', function(Blueprint $t){ $t->id(); $t->foreignId('form_id')->constrained()->cascadeOnDelete(); $t->string('label'); $t->string('name'); $t->string('type')->default('text'); $t->json('options')->nullable(); $t->json('validation')->nullable(); $t->json('conditional')->nullable(); $t->integer('sort_order')->default(0); $t->boolean('is_required')->default(false); $t->string('placeholder')->nullable(); $t->timestamps(); });
        Schema::create('form_submissions', function(Blueprint $t){ $t->id(); $t->foreignId('form_id')->constrained()->cascadeOnDelete(); $t->string('tenant_id')->nullable()->index(); $t->json('data')->nullable(); $t->string('ip')->nullable(); $t->text('user_agent')->nullable(); $t->timestamps(); });
        Schema::create('content_types', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->string('table_name')->nullable(); $t->text('description')->nullable(); $t->string('icon')->nullable(); $t->boolean('is_api_enabled')->default(true); $t->json('fields')->nullable(); $t->timestamps(); });
        Schema::create('content_records', function(Blueprint $t){ $t->id(); $t->foreignId('content_type_id')->constrained()->cascadeOnDelete(); $t->string('tenant_id')->nullable()->index(); $t->uuid('uuid')->nullable()->unique(); $t->json('data')->nullable(); $t->string('status')->default('published'); $t->timestamps(); $t->softDeletes(); });
        Schema::create('workflows', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('trigger_event'); $t->json('conditions')->nullable(); $t->json('actions')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('workflow_runs', function(Blueprint $t){ $t->id(); $t->foreignId('workflow_id')->constrained()->cascadeOnDelete(); $t->string('status')->default('running'); $t->json('payload')->nullable(); $t->text('log')->nullable(); $t->timestamp('started_at')->nullable(); $t->timestamp('finished_at')->nullable(); $t->timestamps(); });
        Schema::create('notification_templates', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('slug')->index(); $t->string('name'); $t->string('channel')->default('mail'); $t->string('subject')->nullable(); $t->text('body')->nullable(); $t->json('variables')->nullable(); $t->timestamps(); });
        Schema::create('webhooks', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('event'); $t->string('url'); $t->string('secret')->nullable(); $t->json('headers')->nullable(); $t->boolean('is_active')->default(true); $t->integer('timeout')->default(10); $t->timestamps(); });
        Schema::create('webhook_logs', function(Blueprint $t){ $t->id(); $t->foreignId('webhook_id')->constrained()->cascadeOnDelete(); $t->string('event'); $t->json('payload')->nullable(); $t->string('status')->default('pending'); $t->integer('attempts')->default(0); $t->text('response')->nullable(); $t->timestamp('next_retry_at')->nullable(); $t->timestamps(); });
        Schema::create('dashboard_widgets', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('type'); $t->string('title'); $t->json('config')->nullable(); $t->integer('sort_order')->default(0); $t->integer('width')->default(4); $t->string('permission')->nullable(); $t->boolean('is_visible')->default(true); $t->timestamps(); });
    }
    public function down(): void { foreach(['dashboard_widgets','webhook_logs','webhooks','notification_templates','workflow_runs','workflows','content_records','content_types','form_submissions','form_fields','forms'] as $tb) Schema::dropIfExists($tb); }
};
