<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('properties', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->text('address')->nullable(); $t->string('city')->nullable(); $t->string('phone')->nullable(); $t->string('email')->nullable(); $t->integer('stars')->default(3); $t->json('meta')->nullable(); $t->timestamps(); });
        Schema::create('room_types', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('property_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('slug')->index(); $t->text('description')->nullable(); $t->decimal('base_price',12,2)->default(0); $t->integer('capacity')->default(2); $t->json('amenities')->nullable(); $t->json('images')->nullable(); $t->timestamps(); });
        Schema::create('rooms', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('property_id')->constrained()->cascadeOnDelete(); $t->foreignId('room_type_id')->constrained()->cascadeOnDelete(); $t->string('number'); $t->string('floor')->nullable(); $t->string('status')->default('available'); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('guests', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->string('id_number')->nullable(); $t->text('address')->nullable(); $t->json('meta')->nullable(); $t->timestamps(); });
        Schema::create('reservations', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('property_id')->constrained()->cascadeOnDelete(); $t->foreignId('room_id')->nullable()->constrained('rooms')->nullOnDelete(); $t->foreignId('guest_id')->constrained()->cascadeOnDelete(); $t->string('number')->unique(); $t->date('check_in'); $t->date('check_out'); $t->string('status')->default('booked'); $t->decimal('total',12,2)->default(0); $t->decimal('paid',12,2)->default(0); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('housekeeping_tasks', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('property_id')->constrained()->cascadeOnDelete(); $t->foreignId('room_id')->constrained()->cascadeOnDelete(); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->string('task'); $t->string('status')->default('pending'); $t->timestamp('due_at')->nullable(); $t->timestamps(); });
        Schema::create('courses', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('category_id')->nullable()->constrained('categories')->nullOnDelete(); $t->foreignId('instructor_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('title'); $t->string('slug')->index(); $t->text('description')->nullable(); $t->decimal('price',12,2)->default(0); $t->string('level')->default('beginner'); $t->string('status')->default('draft'); $t->string('thumbnail')->nullable(); $t->json('meta')->nullable(); $t->timestamps(); });
        Schema::create('lessons', function(Blueprint $t){ $t->id(); $t->foreignId('course_id')->constrained()->cascadeOnDelete(); $t->string('title'); $t->string('slug')->index(); $t->string('content_type')->default('text'); $t->longText('content')->nullable(); $t->string('video_url')->nullable(); $t->integer('duration_minutes')->default(0); $t->integer('sort_order')->default(0); $t->boolean('is_free')->default(false); $t->timestamps(); });
        Schema::create('enrollments', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('course_id')->constrained()->cascadeOnDelete(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('status')->default('active'); $t->integer('progress')->default(0); $t->timestamp('enrolled_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); $t->unique(['course_id','user_id']); });
        Schema::create('quizzes', function(Blueprint $t){ $t->id(); $t->foreignId('course_id')->constrained()->cascadeOnDelete(); $t->foreignId('lesson_id')->nullable()->constrained('lessons')->nullOnDelete(); $t->string('title'); $t->json('questions')->nullable(); $t->integer('passing_score')->default(70); $t->timestamps(); });
        Schema::create('certificates', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('course_id')->constrained()->cascadeOnDelete(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('code')->unique(); $t->timestamp('issued_at')->nullable(); $t->timestamps(); });
        Schema::create('leads', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->string('company')->nullable(); $t->string('source')->nullable(); $t->string('status')->default('new'); $t->decimal('value',14,2)->default(0); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('companies', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->string('website')->nullable(); $t->text('address')->nullable(); $t->string('industry')->nullable(); $t->timestamps(); });
        Schema::create('contacts', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('company_id')->nullable()->constrained('companies')->nullOnDelete(); $t->string('name'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->string('position')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('pipelines', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->json('stages')->nullable(); $t->timestamps(); });
        Schema::create('deals', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('pipeline_id')->constrained()->cascadeOnDelete(); $t->string('stage')->default('new'); $t->string('title'); $t->decimal('value',14,2)->default(0); $t->string('currency')->default('IDR'); $t->foreignId('company_id')->nullable()->constrained('companies')->nullOnDelete(); $t->foreignId('contact_id')->nullable()->constrained('contacts')->nullOnDelete(); $t->date('expected_close')->nullable(); $t->string('status')->default('open'); $t->timestamps(); });
        Schema::create('crm_activities', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('related_type')->nullable(); $t->unsignedBigInteger('related_id')->nullable(); $t->string('type')->default('note'); $t->string('subject'); $t->text('body')->nullable(); $t->timestamp('due_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->timestamps(); });
    }
    public function down(): void { foreach(['crm_activities','deals','pipelines','contacts','companies','leads','certificates','quizzes','enrollments','lessons','courses','housekeeping_tasks','reservations','guests','rooms','room_types','properties'] as $tb) Schema::dropIfExists($tb); }
};
