<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('customers', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('email')->nullable()->index(); $t->string('phone')->nullable(); $t->text('address')->nullable(); $t->string('city')->nullable(); $t->json('meta')->nullable(); $t->integer('total_orders')->default(0); $t->decimal('total_spent',14,2)->default(0); $t->timestamps(); $t->softDeletes(); });
        Schema::create('suppliers', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('email')->nullable(); $t->string('phone')->nullable(); $t->text('address')->nullable(); $t->json('meta')->nullable(); $t->timestamps(); });
        Schema::create('product_categories', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->foreignId('parent_id')->nullable()->constrained('product_categories')->nullOnDelete(); $t->string('image')->nullable(); $t->text('description')->nullable(); $t->timestamps(); });
        Schema::create('products', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('category_id')->nullable()->constrained('product_categories')->nullOnDelete(); $t->unsignedBigInteger('vendor_id')->nullable()->index(); $t->string('name'); $t->string('slug')->index(); $t->string('sku')->nullable()->unique(); $t->text('description')->nullable(); $t->decimal('price',14,2)->default(0); $t->decimal('cost',14,2)->default(0); $t->integer('stock')->default(0); $t->boolean('track_stock')->default(true); $t->boolean('is_active')->default(true); $t->json('attributes')->nullable(); $t->json('images')->nullable(); $t->decimal('weight',10,2)->default(0); $t->decimal('tax_rate',5,2)->default(0); $t->timestamps(); $t->softDeletes(); });
        Schema::create('product_variants', function(Blueprint $t){ $t->id(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('sku')->nullable(); $t->decimal('price',14,2)->default(0); $t->integer('stock')->default(0); $t->json('attributes')->nullable(); $t->timestamps(); });
        Schema::create('coupons', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('code')->unique(); $t->string('type')->default('percent'); $t->decimal('value',12,2)->default(0); $t->decimal('min_order',12,2)->default(0); $t->integer('max_uses')->default(0); $t->integer('used')->default(0); $t->timestamp('starts_at')->nullable(); $t->timestamp('ends_at')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('orders', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->unsignedBigInteger('vendor_id')->nullable()->index(); $t->foreignId('customer_id')->nullable()->constrained('customers')->nullOnDelete(); $t->string('number')->unique(); $t->string('status')->default('pending'); $t->string('payment_status')->default('unpaid'); $t->decimal('subtotal',14,2)->default(0); $t->decimal('discount',14,2)->default(0); $t->decimal('tax',14,2)->default(0); $t->decimal('shipping',14,2)->default(0); $t->decimal('total',14,2)->default(0); $t->string('currency')->default('IDR'); $t->text('notes')->nullable(); $t->json('meta')->nullable(); $t->timestamp('ordered_at')->nullable(); $t->timestamps(); });
        Schema::create('order_items', function(Blueprint $t){ $t->id(); $t->foreignId('order_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->nullable()->constrained('products')->nullOnDelete(); $t->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete(); $t->string('name'); $t->integer('qty')->default(1); $t->decimal('price',14,2)->default(0); $t->decimal('total',14,2)->default(0); $t->timestamps(); });
        Schema::create('payments', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('order_id')->nullable()->constrained('orders')->nullOnDelete(); $t->string('gateway')->default('manual'); $t->string('method')->nullable(); $t->decimal('amount',14,2)->default(0); $t->string('currency')->default('IDR'); $t->string('status')->default('pending'); $t->string('reference')->nullable(); $t->json('meta')->nullable(); $t->timestamps(); });
        Schema::create('inventories', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete(); $t->string('warehouse')->default('default'); $t->integer('qty')->default(0); $t->integer('reserved')->default(0); $t->timestamps(); });
        Schema::create('stock_movements', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete(); $t->string('type'); $t->integer('qty'); $t->string('reference')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
        Schema::create('expenses', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('category')->nullable(); $t->decimal('amount',14,2)->default(0); $t->string('currency')->default('IDR'); $t->text('description')->nullable(); $t->date('spent_at')->nullable(); $t->timestamps(); });
        Schema::create('sales', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('number')->unique(); $t->foreignId('customer_id')->nullable()->constrained('customers')->nullOnDelete(); $t->foreignId('cashier_id')->nullable()->constrained('users')->nullOnDelete(); $t->decimal('subtotal',14,2)->default(0); $t->decimal('discount',14,2)->default(0); $t->decimal('tax',14,2)->default(0); $t->decimal('total',14,2)->default(0); $t->string('payment_method')->default('cash'); $t->decimal('amount_paid',14,2)->default(0); $t->decimal('change',14,2)->default(0); $t->string('status')->default('completed'); $t->timestamp('sold_at')->nullable(); $t->timestamps(); });
        Schema::create('sale_items', function(Blueprint $t){ $t->id(); $t->foreignId('sale_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->nullable()->constrained('products')->nullOnDelete(); $t->string('name'); $t->integer('qty')->default(1); $t->decimal('price',14,2)->default(0); $t->decimal('total',14,2)->default(0); $t->timestamps(); });
        Schema::create('purchases', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('number')->unique(); $t->foreignId('supplier_id')->nullable()->constrained('suppliers')->nullOnDelete(); $t->decimal('subtotal',14,2)->default(0); $t->decimal('tax',14,2)->default(0); $t->decimal('total',14,2)->default(0); $t->string('status')->default('pending'); $t->timestamp('purchased_at')->nullable(); $t->timestamps(); });
        Schema::create('reviews', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('reviewable_type'); $t->unsignedBigInteger('reviewable_id'); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->integer('rating')->default(5); $t->string('title')->nullable(); $t->text('body')->nullable(); $t->string('status')->default('approved'); $t->timestamps(); });
        Schema::create('wishlists', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('product_id')->constrained()->cascadeOnDelete(); $t->timestamps(); $t->unique(['user_id','product_id']); });
    }
    public function down(): void { foreach(['wishlists','reviews','purchases','sale_items','sales','expenses','stock_movements','inventories','payments','order_items','orders','coupons','product_variants','products','product_categories','suppliers','customers'] as $tb) Schema::dropIfExists($tb); }
};
