<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('plans', function(Blueprint $t){ $t->id(); $t->string('name'); $t->string('slug')->unique(); $t->decimal('price',12,2)->default(0); $t->string('currency')->default('IDR'); $t->string('interval')->default('monthly'); $t->json('features')->nullable(); $t->json('limits')->nullable(); $t->boolean('is_active')->default(true); $t->integer('sort_order')->default(0); $t->timestamps(); });
        Schema::create('tenants', function(Blueprint $t){ $t->string('id')->primary(); $t->uuid('uuid')->nullable()->unique(); $t->string('name'); $t->string('slug')->unique(); $t->string('domain')->nullable()->unique(); $t->string('subdomain')->nullable()->unique(); $t->string('status')->default('active'); $t->foreignId('plan_id')->nullable()->constrained('plans')->nullOnDelete(); $t->json('settings')->nullable(); $t->json('quotas')->nullable(); $t->timestamp('trial_ends_at')->nullable(); $t->timestamp('expires_at')->nullable(); $t->timestamps(); });
        Schema::create('tenant_user', function(Blueprint $t){ $t->id(); $t->string('tenant_id'); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->foreignId('role_id')->nullable()->constrained('roles')->nullOnDelete(); $t->timestamps(); });
        Schema::create('tenant_domains', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->index(); $t->string('domain')->unique(); $t->boolean('is_primary')->default(false); $t->boolean('is_verified')->default(false); $t->timestamps(); });
        Schema::create('subscriptions', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->index(); $t->foreignId('plan_id')->constrained()->cascadeOnDelete(); $t->string('status')->default('trial'); $t->timestamp('trial_ends_at')->nullable(); $t->timestamp('current_period_start')->nullable(); $t->timestamp('current_period_end')->nullable(); $t->timestamp('cancelled_at')->nullable(); $t->timestamps(); });
        Schema::create('licenses', function(Blueprint $t){ $t->id(); $t->string('license_key')->unique(); $t->string('product'); $t->string('customer')->nullable(); $t->string('domain')->nullable(); $t->string('status')->default('active'); $t->json('features')->nullable(); $t->integer('max_activations')->default(1); $t->timestamp('expires_at')->nullable(); $t->timestamp('support_expires_at')->nullable(); $t->string('version_entitlement')->nullable(); $t->timestamp('last_checked_at')->nullable(); $t->timestamps(); });
        Schema::create('license_activations', function(Blueprint $t){ $t->id(); $t->foreignId('license_id')->constrained()->cascadeOnDelete(); $t->string('domain'); $t->string('ip')->nullable(); $t->timestamp('activated_at')->nullable(); $t->timestamps(); });
        Schema::create('backups', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('type')->default('full'); $t->string('disk')->default('local'); $t->string('path')->nullable(); $t->bigInteger('size')->default(0); $t->string('status')->default('pending'); $t->text('log')->nullable(); $t->timestamp('started_at')->nullable(); $t->timestamp('finished_at')->nullable(); $t->timestamps(); });
        Schema::create('update_logs', function(Blueprint $t){ $t->id(); $t->string('type'); $t->string('slug'); $t->string('from_version')->nullable(); $t->string('to_version')->nullable(); $t->string('status')->default('pending'); $t->text('log')->nullable(); $t->timestamp('started_at')->nullable(); $t->timestamp('finished_at')->nullable(); $t->timestamps(); });
        Schema::create('audit_logs', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action'); $t->string('entity_type')->nullable(); $t->string('entity_id')->nullable(); $t->text('old_values')->nullable(); $t->text('new_values')->nullable(); $t->string('ip')->nullable(); $t->text('user_agent')->nullable(); $t->timestamps(); });
        Schema::create('login_histories', function(Blueprint $t){ $t->id(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('ip')->nullable(); $t->text('user_agent')->nullable(); $t->string('status')->default('success'); $t->string('failed_reason')->nullable(); $t->timestamp('logged_in_at')->nullable(); $t->timestamps(); });
        Schema::create('tasks', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->string('title'); $t->text('description')->nullable(); $t->string('status')->default('open'); $t->string('priority')->default('medium'); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('due_at')->nullable(); $t->timestamp('completed_at')->nullable(); $t->timestamps(); });
        Schema::create('task_comments', function(Blueprint $t){ $t->id(); $t->foreignId('task_id')->constrained()->cascadeOnDelete(); $t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete(); $t->text('body'); $t->timestamps(); });
    }
    public function down(): void { foreach(['task_comments','tasks','login_histories','audit_logs','update_logs','backups','license_activations','licenses','subscriptions','plans','tenant_domains','tenant_user','tenants'] as $tb) Schema::dropIfExists($tb); }
};
