<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('member_profiles', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('display_name'); $t->string('gender')->nullable(); $t->date('birthdate')->nullable(); $t->string('city')->nullable(); $t->string('occupation')->nullable(); $t->string('education')->nullable(); $t->integer('height')->nullable(); $t->string('marital_status')->nullable(); $t->text('bio')->nullable(); $t->json('interests')->nullable(); $t->json('photos')->nullable(); $t->boolean('is_verified')->default(false); $t->boolean('is_premium')->default(false); $t->string('status')->default('active'); $t->timestamps(); });
        Schema::create('member_preferences', function(Blueprint $t){ $t->id(); $t->foreignId('member_id')->constrained('member_profiles')->cascadeOnDelete(); $t->integer('min_age')->default(18); $t->integer('max_age')->default(99); $t->json('genders')->nullable(); $t->json('cities')->nullable(); $t->string('education')->nullable(); $t->json('meta')->nullable(); $t->timestamps(); });
        Schema::create('member_likes', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('from_member_id')->constrained('member_profiles')->cascadeOnDelete(); $t->foreignId('to_member_id')->constrained('member_profiles')->cascadeOnDelete(); $t->timestamps(); $t->unique(['from_member_id','to_member_id']); });
        Schema::create('member_favorites', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('member_id')->constrained('member_profiles')->cascadeOnDelete(); $t->foreignId('favorited_id')->constrained('member_profiles')->cascadeOnDelete(); $t->timestamps(); });
        Schema::create('member_blocks', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('member_id')->constrained('member_profiles')->cascadeOnDelete(); $t->foreignId('blocked_id')->constrained('member_profiles')->cascadeOnDelete(); $t->string('reason')->nullable(); $t->timestamps(); });
        Schema::create('member_reports', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('reporter_id')->constrained('member_profiles')->cascadeOnDelete(); $t->foreignId('reported_id')->constrained('member_profiles')->cascadeOnDelete(); $t->string('reason'); $t->text('details')->nullable(); $t->string('status')->default('pending'); $t->timestamps(); });
        Schema::create('memberships', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('member_id')->constrained('member_profiles')->cascadeOnDelete(); $t->string('plan')->default('free'); $t->timestamp('starts_at')->nullable(); $t->timestamp('ends_at')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::create('vendors', function(Blueprint $t){ $t->id(); $t->string('tenant_id')->nullable()->index(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('slug')->index(); $t->text('description')->nullable(); $t->string('logo')->nullable(); $t->string('status')->default('pending'); $t->decimal('commission_rate',5,2)->default(10); $t->decimal('balance',14,2)->default(0); $t->timestamps(); });
        Schema::create('vendor_payouts', function(Blueprint $t){ $t->id(); $t->foreignId('vendor_id')->constrained()->cascadeOnDelete(); $t->decimal('amount',14,2)->default(0); $t->string('currency')->default('IDR'); $t->string('status')->default('pending'); $t->timestamp('paid_at')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
    }
    public function down(): void { foreach(['vendor_payouts','vendors','memberships','member_reports','member_blocks','member_favorites','member_likes','member_preferences','member_profiles'] as $tb) Schema::dropIfExists($tb); }
};
